# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


SET(CPACK_BINARY_BUNDLE "")
SET(CPACK_BINARY_CYGWIN "")
SET(CPACK_BINARY_DEB "")
SET(CPACK_BINARY_DRAGNDROP "")
SET(CPACK_BINARY_NSIS "")
SET(CPACK_BINARY_OSXX11 "")
SET(CPACK_BINARY_PACKAGEMAKER "")
SET(CPACK_BINARY_RPM "")
SET(CPACK_BINARY_STGZ "")
SET(CPACK_BINARY_TBZ2 "")
SET(CPACK_BINARY_TGZ "")
SET(CPACK_BINARY_TZ "")
SET(CPACK_BINARY_WIX "")
SET(CPACK_BINARY_ZIP "")
SET(CPACK_CMAKE_GENERATOR "Xcode")
SET(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
SET(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
SET(CPACK_GENERATOR "TGZ;TBZ2;TZ")
SET(CPACK_IGNORE_FILES "CVS;[.]svn;[.]git;[.]AppleDouble;[.]#.*;#.*;.*[.]kdev4;.*~;build.*;doc/html/*;doc/latex/*;doc/html-Board/*")
SET(CPACK_INSTALLED_DIRECTORIES "/Users/davidcoeurjolly/Sources/DGtal;/")
SET(CPACK_INSTALL_CMAKE_PROJECTS "")
SET(CPACK_INSTALL_PREFIX "/usr/local")
SET(CPACK_MODULE_PATH "/Users/davidcoeurjolly/Sources/DGtal/cmake")
SET(CPACK_NSIS_CONTACT "dgtal@liris.cnrs.fr")
SET(CPACK_NSIS_DISPLAY_NAME "DGtal 0.7.beta")
SET(CPACK_NSIS_INSTALLER_ICON_CODE "")
SET(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
SET(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
SET(CPACK_NSIS_PACKAGE_NAME "DGtal 0.7.beta")
SET(CPACK_OUTPUT_CONFIG_FILE "/Users/davidcoeurjolly/Sources/DGtal/build-xcode/CPackConfig.cmake")
SET(CPACK_PACKAGE_CONTACT "dgtal@liris.cnrs.fr")
SET(CPACK_PACKAGE_DEFAULT_LOCATION "/")
SET(CPACK_PACKAGE_DESCRIPTION_FILE "/Users/davidcoeurjolly/Sources/DGtal/README")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "DGtal Project")
SET(CPACK_PACKAGE_FILE_NAME "DGtal-0.7.beta-Source")
SET(CPACK_PACKAGE_INSTALL_DIRECTORY "DGtal 0.7.beta")
SET(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "DGtal 0.7.beta")
SET(CPACK_PACKAGE_NAME "DGtal")
SET(CPACK_PACKAGE_RELOCATABLE "true")
SET(CPACK_PACKAGE_VENDOR ".")
SET(CPACK_PACKAGE_VERSION "0.7.beta")
SET(CPACK_PACKAGE_VERSION_MAJOR "0")
SET(CPACK_PACKAGE_VERSION_MINOR "7")
SET(CPACK_PACKAGE_VERSION_PATCH "beta")
SET(CPACK_RESOURCE_FILE_LICENSE "/Users/davidcoeurjolly/Sources/DGtal/LICENSE")
SET(CPACK_RESOURCE_FILE_README "/usr/local/Cellar/cmake/2.8.11.2/share/cmake/Templates/CPack.GenericDescription.txt")
SET(CPACK_RESOURCE_FILE_WELCOME "/usr/local/Cellar/cmake/2.8.11.2/share/cmake/Templates/CPack.GenericWelcome.txt")
SET(CPACK_SET_DESTDIR "OFF")
SET(CPACK_SOURCE_CYGWIN "")
SET(CPACK_SOURCE_GENERATOR "TGZ;TBZ2;TZ")
SET(CPACK_SOURCE_IGNORE_FILES "CVS;[.]svn;[.]git;[.]AppleDouble;[.]#.*;#.*;.*[.]kdev4;.*~;build.*;doc/html/*;doc/latex/*;doc/html-Board/*")
SET(CPACK_SOURCE_INSTALLED_DIRECTORIES "/Users/davidcoeurjolly/Sources/DGtal;/")
SET(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/Users/davidcoeurjolly/Sources/DGtal/build-xcode/CPackSourceConfig.cmake")
SET(CPACK_SOURCE_PACKAGE_FILE_NAME "DGtal-0.7.beta-Source")
SET(CPACK_SOURCE_STRIP_FILES "")
SET(CPACK_SOURCE_TBZ2 "ON")
SET(CPACK_SOURCE_TGZ "ON")
SET(CPACK_SOURCE_TOPLEVEL_TAG "Darwin-Source")
SET(CPACK_SOURCE_TZ "ON")
SET(CPACK_SOURCE_ZIP "OFF")
SET(CPACK_STRIP_FILES "")
SET(CPACK_SYSTEM_NAME "Darwin")
SET(CPACK_TOPLEVEL_TAG "Darwin-Source")
SET(CPACK_WIX_SIZEOF_VOID_P "8")
