# Generated by CMake 2.8.11.2

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget DGtal)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target DGtal
add_library(DGtal SHARED IMPORTED)

# Import target "DGtal" for configuration "Debug"
set_property(TARGET DGtal APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(DGtal PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "/usr/local/lib/libhdf5_hl.dylib;/usr/local/lib/libhdf5.dylib;/usr/local/lib/libsz.dylib;/usr/lib/libz.dylib;/usr/lib/libdl.dylib;/usr/lib/libm.dylib"
  IMPORTED_LOCATION_DEBUG "/Users/davidcoeurjolly/Sources/DGtal/build-xcode/src/Debug/libDGtal.dylib"
  IMPORTED_NO_SONAME_DEBUG "TRUE"
  )

# Import target "DGtal" for configuration "Release"
set_property(TARGET DGtal APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(DGtal PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "/usr/local/lib/libhdf5_hl.dylib;/usr/local/lib/libhdf5.dylib;/usr/local/lib/libsz.dylib;/usr/lib/libz.dylib;/usr/lib/libdl.dylib;/usr/lib/libm.dylib"
  IMPORTED_LOCATION_RELEASE "/Users/davidcoeurjolly/Sources/DGtal/build-xcode/src/Release/libDGtal.dylib"
  IMPORTED_NO_SONAME_RELEASE "TRUE"
  )

# Import target "DGtal" for configuration "MinSizeRel"
set_property(TARGET DGtal APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(DGtal PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_MINSIZEREL "/usr/local/lib/libhdf5_hl.dylib;/usr/local/lib/libhdf5.dylib;/usr/local/lib/libsz.dylib;/usr/lib/libz.dylib;/usr/lib/libdl.dylib;/usr/lib/libm.dylib"
  IMPORTED_LOCATION_MINSIZEREL "/Users/davidcoeurjolly/Sources/DGtal/build-xcode/src/MinSizeRel/libDGtal.dylib"
  IMPORTED_NO_SONAME_MINSIZEREL "TRUE"
  )

# Import target "DGtal" for configuration "RelWithDebInfo"
set_property(TARGET DGtal APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(DGtal PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELWITHDEBINFO "/usr/local/lib/libhdf5_hl.dylib;/usr/local/lib/libhdf5.dylib;/usr/local/lib/libsz.dylib;/usr/lib/libz.dylib;/usr/lib/libdl.dylib;/usr/lib/libm.dylib"
  IMPORTED_LOCATION_RELWITHDEBINFO "/Users/davidcoeurjolly/Sources/DGtal/build-xcode/src/RelWithDebInfo/libDGtal.dylib"
  IMPORTED_NO_SONAME_RELWITHDEBINFO "TRUE"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
