name: "Setup-MacOs"
description: "Set up a macos environment"
inputs:
  python-version:
    description: "Version of python to use"
    required: true
    default: "3.9"

runs:
  using: "composite"
  steps:
     - name: Set up Python ${{ inputs.python-version }}
       uses: actions/setup-python@v5
       with: 
          python-version: ${{ inputs.python-version }}

     - name: Install macOS deps
       shell: bash
       run: brew install ninja libomp ccache cgal