# Generated by CMake 2.8.7

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target DGtal
ADD_LIBRARY(DGtal SHARED IMPORTED)

# Import target "DGtal" for configuration ""
SET_PROPERTY(TARGET DGtal APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(DGtal PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "/usr/lib/libboost_program_options-mt.a;/usr/lib/i386-linux-gnu/libqglviewer-qt4.so;/usr/lib/i386-linux-gnu/libGLU.so;/usr/lib/i386-linux-gnu/libGL.so;/usr/lib/i386-linux-gnu/libSM.so;/usr/lib/i386-linux-gnu/libICE.so;/usr/lib/i386-linux-gnu/libX11.so;/usr/lib/i386-linux-gnu/libXext.so;/usr/lib/i386-linux-gnu/libQtOpenGL.so;/usr/lib/i386-linux-gnu/libQtGui.so;/usr/lib/i386-linux-gnu/libQtXml.so;/usr/lib/i386-linux-gnu/libQtCore.so"
  IMPORTED_LOCATION_NOCONFIG "/home/anisbenyoub/Libraries/DGtal/buildQGL/src/libDGtal.so"
  IMPORTED_SONAME_NOCONFIG "libDGtal.so"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
# Generated by CMake 2.8.7

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target DGtalIO
ADD_LIBRARY(DGtalIO SHARED IMPORTED)

# Import target "DGtalIO" for configuration ""
SET_PROPERTY(TARGET DGtalIO APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
SET_TARGET_PROPERTIES(DGtalIO PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG "DGtal;/usr/lib/libboost_program_options-mt.a;/usr/lib/i386-linux-gnu/libqglviewer-qt4.so;/usr/lib/i386-linux-gnu/libGLU.so;/usr/lib/i386-linux-gnu/libGL.so;/usr/lib/i386-linux-gnu/libSM.so;/usr/lib/i386-linux-gnu/libICE.so;/usr/lib/i386-linux-gnu/libX11.so;/usr/lib/i386-linux-gnu/libXext.so;/usr/lib/i386-linux-gnu/libQtOpenGL.so;/usr/lib/i386-linux-gnu/libQtGui.so;/usr/lib/i386-linux-gnu/libQtXml.so;/usr/lib/i386-linux-gnu/libQtCore.so"
  IMPORTED_LOCATION_NOCONFIG "/home/anisbenyoub/Libraries/DGtal/buildQGL/src/libDGtalIO.so"
  IMPORTED_SONAME_NOCONFIG "libDGtalIO.so"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
