name: "DGtal-cmake"
description: "Apply CMake to DGtal"
inputs:
  dgtal:
    description: "CMakelists location"
    default: ${{ runner.workspace }}/DGtal
    required: true

  build-dir:
    description: "Directory to setup cmake in"
    default: ${{ runner.workspace }}/build
    required: true

  build-type:
    description: "Type of build Release or Debug"
    default: "Release"

  build-config: 
    description: "Additionnal configuration to give to cmake"
    default: ""

  cache-deps-path:
    description: "If non-empty, specify path to cache folder"
    default: ${{ runner.workspace }}/cache 
    required: true

  test:
    description: "Whether to run tests or not. This requires the proper build-config and environment variable TESTBLACKLIST to be set."
    type: boolean
    default: false

  test-threshold:
    description: "Randomize test threshold"
    default: "10"

  test-blacklist:
    description: "Tests to blacklist"
    default: ""

  test-whitelist:
    description: "Tests to whitelist"
    default: ""

runs:
  using: "composite"
  steps:
    - name: "Standardize to linux-style path"
      shell: bash
      # Mixed-path are sometimes not working with CMake and Conan in bash shell
      # Avoid DGTAL_DIR for potential conflicts with CMake find_package
      run: |
        echo "DGTAL_PATH=$(echo '${{ inputs.dgtal }}' | sed s/\\\\/\\//g)" >> "$GITHUB_ENV"
        echo "DGTAL_BUILD_PATH=$(echo '${{ inputs.build-dir }}' | sed s/\\\\/\\//g)" >> "$GITHUB_ENV"
        echo "CPM_SOURCE_CACHE=$(echo '${{ inputs.cache-deps-path }}' | sed s/\\\\/\\//g)" >> "$GITHUB_ENV"
        echo "CACHE_ID=$(gh run list --workflow '${{ github.workflow }}' --branch CacheImprove --limit 1 --json databaseId --jq '.[0].databaseId')" >> "$GITHUB_ENV"

    - name: "Restoring cpm cache"
      id: restore-cpm-cache
      uses: actions/download-artifact@v4
      continue-on-error: true 
      with:
        path: ${{ env.CPM_SOURCE_CACHE }}
        name: ${{ runner.os }}-cpm-cache
        run-id: ${{ env.CACHE_ID }}
        github-token: ${{ github.token }}

    - name: "Create build directory"
      shell: bash
      run: |
        cmake -E make_directory $DGTAL_BUILD_PATH

    - name: Install additionnal dependancies (windows)
      if: ${{ runner.os == 'Windows' }}
      shell: bash
      working-directory: ${{ inputs.build-dir }}
      run: |
        conan install $DGTAL_PATH --build=missing -s:a compiler.cppstd=20

    - name: "Conan Cache"
      if: ${{ runner.os == 'Windows' }}
      uses: actions/cache@v4
      with:
        path: ~/.conan2
        key: ${{ runner.os }}-conan2-${{ matrix.BUILD_TYPE }}

    - name: Configure CMake
      shell: bash
      working-directory: ${{ inputs.build-dir }} 
      run: |
        cmake $DGTAL_PATH -DCMAKE_BUILD_TYPE=${{ inputs.build-type }} -DDGTAL_RANDOMIZED_TESTING_WHITELIST="${{ inputs.test-whitelist }}" -DDGTAL_RANDOMIZED_TESTING_THRESHOLD="${{ inputs.test-threshold }}" ${{ inputs.build-config }}

    - name: Build
      shell: bash
      working-directory: ${{ inputs.build-dir }} 
      run: cmake --build . --config ${{ inputs.build-type }} --parallel 3
    
    - name: Debug
      shell:
      run:
        echo "${{ github.ref_name }} / $GITHUB_REF_NAME"

    - name: Uploading artifacts
      # if: ${{ github.ref_name == 'CacheImprove' }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ runner.os }}-cpm-cache
        path: ${{ env.CPM_SOURCE_CACHE }}
        retention-day: 89 # Limit is 90 days for free use 

    - name: Perform tests
      if: ${{ inputs.test == 'true'}}
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: |
           echo ctest -C ${{ inputs.build-type }}  --output-on-failure -E ${{ inputs.test-blacklist }}
           ctest -C ${{ inputs.build-type }} --output-on-failure -E ${{ inputs.test-blacklist }}
